---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: '{{ .Values.clusterName }}'
  namespace: '{{ .Values.clusterName }}'
spec:
  clusterDeploymentRef:
    name: '{{ .Values.clusterName }}'
  provisionRequirements:
{{- if and .Values.worker (gt .Values.workers 0) }}
    workerAgents: {{ .Values.workers}}
{{- end }}
    controlPlaneAgents: {{ .Values.controlPlane }}
  mastersSchedulable: {{ .Values.mastersSchedulable }}
  imageSetRef:
    name: '{{ .Values.imageSet }}'
  networking:
    networkType: 'OVNKubernetes'
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    serviceNetwork:
    - 172.30.0.0/16
    machineNetwork:
    - cidr: {{ .Values.machineNetwork }}
  apiVIP: {{ .Values.apiVIP }}
  ingressVIP: {{ .Values.ingressVIP }}
  sshPublicKey: '{{ .Values.sshPublicKey }}'
