apiVersion: v1
kind: Secret
metadata:
  name: k8s-sno-cluster
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
    app.kubernetes.io/instance: app-of-apps
  annotations:
    managed-by: argocd.argoproj.io
stringData:
  name: k8s-sno
  server: 'https://kubernetes.default.svc'
type: Opaque
