---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: k8s-sno-cluster
  namespace: openshift-gitops
spec:
  encryptedData:
    name: AgC2KizXfK8wQkvCbsJVR5+XvF2vQ1GAMDLV38arhKTHjHp8wMNYMkKfTKBUC1RK/kFttFTQG+BOp3bXkitkCrijWhqNPrFZ6yW+wTk6KAcvHZ/uwAenA1hiVvFOt+Fqns+cYxhyNGrb9Hdz1tYWG5aZoy6yT63zs826aTrPQ45Lql9I6XwSbfEphOP0w364ee0aSgKTkJE44D7Z1PK5O7Tnz0UqJ7CSvMATSTR+MmLZdQH7+W24NmKZhF8xL86Wtr0+WNIT7zOeumFd3dOKd/T7z4yFInCy5GCOCUm0jg3mSmyvUMI/vceNTHgbIKrYpEP15MaFYdqT6pi/4FVmhvu2lemcDj421aONmwac0rYRslcvHAPTReOSZRWAKuCkbqWKvSrrjjj06giv29r0rXiO4kMHXivs1BWILULfYfuplIpFt+d0+vorr71GNd2ngBjWuXabLmlj3fGNPwAoZ8ioPPcNpV9ktuaZzyPni+Y6fyOkBgf7ZJTcwqsOLWccPp5Am7vJhGpzkqXnXLiTmOUR4QX/crSZsSrNakAm3quZvEBg/auqKjfG5HD+MFnnTSXroPRgOFciTGWq+XbY6RY7EDe9syc8JEDQYue2wwy9jNF2wFmr+sSvikf9zH2Kwfei7gmLYgbFYTju7y+UPcJgXUeXz2qbZCfxGeDXNg545EFTV6jq1Ls8FfOa0Zpmw9P7DocDTn3V
    namespaces: AgDp+UNZ0q7ujzckOAqUHFpL7jSPQUcZFne5SyKtw/dUQwc+fTPVGEfqEsMBKqwLyqD7zo2ZepYCutZBPaHl5ONue1WW02YcTfqRWhgUCW4yJT4GbL5PJaC/QlsT5RSsjI+jkh2LcPNQEhDvHBdVpRJTxsXLwIrt/NNwGB6WTQ7nw7cSTSGp+JM7fT4Gx4/CUsqy7oQQ+Ksr2ykBD9jjjbf+ErW2aRpHU4Lkf6lHIBSRsb+Ma2sXFVoUtRFkbCpVEnQBSE0VFFtK4g9AectYvnLOCN0E7OEYHqGRxGlwlAKvvCceCpgSNsTuuP7uI4ibkqVgYONm6myGRJ7hxK+Gsq5OPf9hbDPK8v/HP6XbN63LjrMv98Zv7ZGYkCpi+zykJgdFpuGPpYnKxfriFG+mEh3ZzugLtvYBWzPfdrmhq+Ub8gXhtERVwewAEF6q0D3GQEO0EuPWTwP/NoRS+apjmPA/rB0GUk/Mcq5jrXNwDaf7laUtUMwzEzJ0+Rx7Di+JQeRuYGjZONg3z4gh89vLM4c/phT5fsJ6OlcLSU3e3gqC7J7hpTYUphVEoctGnJpoENxFjuqTgJ180MbAzTJFSh2BSkdVu5whPSpEJXUFOLcvXK6y7mrXxEV3H5Wl4WsJGUk9nXixowrVlgwtbjMzWD/ILkxXcNSQAGS6o16JJPad7tcTh6I1VdMXZSUW6nsk4Qw=
    server: AgDzbPyZ1x4T4dYHk1kOvQtVt6+ofoabTlNdfPQq59dAHWIl/mDnTm8SEbm8B/drTc/G5QxM4nRtrz5juRynxwef25+q9QgRKnofkddiso4KBxE1PW7WDm6uBBJEeVRvxVsJk1ZHtnoCJBpVoOVWZu7Du1X0i81Zwm0F6t6vG/k9+kO0m1c6ASx7jnBU0yyiUfq65jimFnJkIK/9zq4GYRIDs17FIXU6N5Bxmz3uZiudzS2jjXp55uss4HjovRNSE8lYZ9d7fX9UnxYsksFwIB8SDDUUmAmAlcq3AcV9rxNi/uwN8cTVUbpRjY/pMmdNdrw5Tw2sPu7r/u06AM8tFjltpPmwNiLM62U/u8W7QeQRJa8kloPSLp6XB3hHh0/OvGb5I3T8kxyP6/968O2O0yDAz8pcM3e/xlm7TW7Eu2ibuFYgc40D7VSM6HmWv0F7zrNJZfiQtpvXyg76QNW6Qbk8nRRGZt6Q/cGi0T+roPHiyS6gT32J90rpa+wsxAX5DUS6n7foEnTg9YDLKMBMqeuRUYllkt3HeIudz9X2xwQL6Hu3YXtbPGv3sF7efc+UfbwMxYupvym3nWet8R8g5naEryLuchlkUzqtqiBVKuCwch0Jw+Oftb2/VxAS1h/h4l43Mfl3UUKyLYkvG9UH3fnJzUmH4VXeD5FEj5v0Pj3rlhN0OlHp8u+1OpId1RbxXaY5WSSw3Wga3qX8L8baYZBAApRP1QsOaNH4vbSwApw=
  template:
    metadata:
      annotations:
        managed-by: argocd.argoproj.io
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: app-of-apps
        argocd.argoproj.io/secret-type: cluster
      name: k8s-sno-cluster
      namespace: openshift-gitops
    type: Opaque
