---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: k8s-sno-cluster
  namespace: gitops
spec:
  encryptedData:
    name: AgA7bR1chWpt1KfNT8D1Bc1QSVbXlbj1V41CVbGWEqDC23WWqAaNUI+LRFQX+cRYeZUXqH6zUPGp3iPl8HygOWvmF4+SBDnEq8AOqTxTWjfJjohEV4AEy+9fxADLfvoTP1Z4w3quSUFt2aXFfYAamJzCWnU/0NxnxT2kPYLKtuAK5PWBpKkaU6N+Qe9MtMj2L6lXxWQHj4Hz7LpSGQ1Yi7irSOZpemA5ZkfqoOw68mAduN+hW4kvcklMUYxkeKiTP4HaLmLtupIPKpyQDPjV2MJnuZFB6zxhzrS8U+Y1hHAo7l51+oDPVKVDhUvcperU58VOwt9xIMQ2vQxu4rCUJZXLpQs4FOSjMwOE8Y5Sm32OUl2AypUp+m5giMQ9eq1Hn/aTdWS1Hoz+UAQOAk7YpugciJIciXOlDpsecr81dg/GizWIo36F2RlRBhaWJ7FWqwfLGFJ4ZRO+E85G/zW3Psg30sqo/9Kf4+LuWznyXMb/0beJyxbxzhEPMXazfpkfiUu6ahXZy3R1uj/WPfu37M6a0r+5WwON7pMtII7KUu+Lc8VQVLUr5QfUzVN5yOui3NNXTHuiHeE1IDWIkJv1/wRq+4yW0dV+hyKJca+dk8YSMZGFZThcoMik3Dygk8Hvn11Pssl03AZ1eT7kAvYMEYyS64fkmQ1YKd1QuTDD0CJmDSwlJpp7UgnDNi74Gye3NZPdTqcmmroF
    server: AgAvw2bEvLOAlLssQC+Oux9GoyDjhfH+1C//FivNIE4wvj1PwLqteyMZwesqASydfw2g5E1Q7SarnySxsCxuZpx+f1GXYlnYyfJfC4ho2ujrcRGHyyOr/klDRmEX+o0nAlPhfdICa1qy6gxJ/Hc35wRPEWqc9kfEyIjWk336uw9Fm83ylZ/rmCoxPZpufC5V2dZUsk44JqR9J/2NjNcU20csieVTJ8Ccox+eNPC/L5BuMQyZO0a+bLRLcnrQA5XJTtYx70mgkEiZExWZpPRubyrAjU1DjG7HaaBwOUoowFvOe1/9nDepCgl1QlmwWQvgBteC+v6JnITfAEI2RL1gLn6gzip1QtDyOiGkNpqQa0bZd7jAomYTxgdNiaOdC4WjYABTlQJg8I3rOGQg9A3TpM8kVwW2HSuNFXVuFNJGj2StNTtmv2/A5jrycQZeAgVJWQgSlE0QD3MLiNz9jQt/Xk+GSeX49XKjxaynyYTKC/k4B9mrnpj49csW669LonKrJfbYCj8bO6PC99BMqjWNgP0giLyf9LUIuNat4tBlI3I7bYt4YTIEzU3HLSsbCCUydy5FenMtmTNMxJXzlHlq5TFV1dZ4Oflnh6rQB9Xp2IZJBs8DQ3kOyIgJnep+zlF0qOKXv2diEOWA880Nbj52IzOaQAWLNs7YnUwynF6DmWQSbzIuqkY9059wkM4EUuiAKZHdLbPL+lGIdRI1/ZQNDrJ+kSNidOplafqlvlBeNNM=
  template:
    metadata:
      annotations:
        managed-by: argocd.argoproj.io
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: cluster
      name: k8s-sno-cluster
      namespace: gitops
    type: Opaque
