apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: key-vault-provider
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    tenantID: redhat0.onmicrosoft.com
    keyvaultName: "svaughan-kvstore" # watsonx-poc-kv
    objects: |
      array:
      {{- range .Values.secretsMap }}
        {{- range .secrets }}
        - |
          objectName: {{ .kvName }}
          objectType: secret
        {{- end }}
      {{- end }}
  secretObjects:
  {{- range .Values.secretsMap }}
  - secretName: {{ .secretName }}
    type: Opaque
    data:
    {{- range .secrets }}
    - key: {{ .secretKey }}
      objectName: {{ .kvName }}
    {{- end }}
  {{- end }}
