apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.clusterProject }}
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: cluster-specific platform configuration
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - argocd-{{ .Values.clusterProject}}
  sourceRepos:
    - 'git@github.com:sean-vaughan/openshift.git'
