apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-azure-secrets-provider
  namespace: azure-secrets-store-verification
spec:
  parameters:
    objects: |
      array:
        - |
          objectName: secret1
          objectType: secret
  secretObjects:
  - secretName: test-secret
    type: Opaque
    data:
    - key: test-secret1
      objectName: secret1
