apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvc-autosize-cron
  namespace: pvc-auto-expansion
---
# Cluster-wide PVC read/patch (so one job can manage any labeled PVC)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvc-autosize-cron
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pvc-autosize-cron
subjects:
  - kind: ServiceAccount
    name: pvc-autosize-cron
    namespace: pvc-auto-expansion
roleRef:
  kind: ClusterRole
  name: pvc-autosize-cron
  apiGroup: rbac.authorization.k8s.io
---
# Allow querying cluster metrics (Thanos Querier)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pvc-autosize-cron-metrics
subjects:
  - kind: ServiceAccount
    name: pvc-autosize-cron
    namespace: pvc-auto-expansion
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
