apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: open-cluster-management-
  annotations:
    olm.providedAPIs: MultiClusterHub.v1.operator.open-cluster-management.io
  namespace: open-cluster-management
spec:
  targetNamespaces:
    - open-cluster-management
  upgradeStrategy: Default