---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
  - git:
      repoURL: 'https://github.com/sean-vaughan/openshift.git'
      revision: HEAD
      directories:
      - path: clusters/*/*
      values:
        appName: "{{ .path.basename }}"
        appPath: "{{ .path.path }}"
        cluster: "{{ .path.segments | index 1 }}"
  # - git:
  #     repoURL: 'git@github.com:sean-vaughan/openshift.git'
  #     revision: HEAD
  #     files:
  #     - path: "clusters/k8s-sno/*.yaml"
  #     values:
  #       app:
  #         name: "{{ .path.filename | trimSuffix '.yaml' }}"
  #         path: "apps/{{ .path.filename | trimSuffix '.yaml' }}"
  #         valuesFile: "clusters/k8s-sno/{{ .path.filename }}"
  template:
    metadata:
      name: '{{ .values.appName }}'
    spec:
      project: "{{ cluster }}"
      source:
        repoURL: 'git@github.com:sean-vaughan/openshift.git'
        targetRevision: HEAD
        path: '{{ .values.appPath }}'
      destination:
        server: https://kubernetes.default.svc
        # namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 2
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
