apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: openshift # i.e. ocp-devops
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: cluster platform configuration
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - '*'
  sourceRepos:
    - 'git@github.com:sean-vaughan/openshift.git'
