
resources:
- app-of-apps.yaml
- argo-project.yaml
- sealed-repo.yaml
- argo-server.yaml
- namespace.yaml
- subscription.yaml
- operator-group.yaml
- operator-namespace.yaml

labels:
  - pairs:
      app.kubernetes.io/instance: openshift-gitops
      app.kubernetes.io/name: openshift-gitops
      app.kubernetes.io/part-of: openshift-gitops
