cluster: k8s-sno # Cluster Deployment is for k8s-1 but resources reside on hub cluster k8s-sno
localHelmValues: true

clusterName: k8s-1
sshPublicKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOjJxh/yC65t0ZAKydvFIifj1San9Z8+no2EX0Bc0izy'
apiVIP: 10.0.2.101
ingressVIP: 10.0.2.102
machineNetwork: 10.0.2.0/24
