---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - list:
          elements: [] # specify via kustomize overlay
      # This generator handles `clusters/<cluster-name>/<app-name>.yaml` files
      # which may contain argo app overrides.
      # - Simply touch the `clusters/<cluster-name>/<app-name>.yaml`` file to include the
      #   `sources/<app-name> app on the cluster.
      # - Or, create a `clusters/<cluster-name>/<app-name>.yaml`` file with argo-app overrides.
      - git:
          repoURL: 'https://github.com/sean-vaughan/openshift.git'
          revision: HEAD
          files:
          - path: 'clusters/{{ .clusterName }}/*.yaml'

  # This ignoreDifferences policy allows changes in the ArgoCD UI to be
  # respected and not overwritten by the git Sync.
  ignoreApplicationDifferences:
  - jqPathExpressions:
    - .spec.source.repoURL
    - .spec.source.targetRevision
    - .spec.source.path
    - .spec.syncPolicy

  template:
    metadata:
      name: '{{ default (print .clusterName "---" (trimSuffix ".yaml" .path.filename)) .metadata.name }}'
    spec:
      destination:
        name: '{{ default .clusterName .spec.destination.name }}'
        namespace: '{{ default "openshift-gitops" .spec.destination.namespace }}'
      project: '{{ default "openshift" .spec.project }}'
      source:
        path: '{{ default (printf "sources/%s" (trimSuffix ".yaml" .path.filename)) .spec.source.path }}'
        repoURL: '{{ default "git@github.com:sean-vaughan/openshift.git" .spec.source.repoURL }}'
        targetRevision: '{{ default "HEAD" .spec.source.targetRevision }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 2
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true

  templatePatch: |
    {{- if .metadata }}
    metadata:
      {{ toYaml .metadata | nindent 2}}
    {{- end }}
    {{- if .spec }}
    spec:
      {{ toYaml .spec | nindent 2 }}
    {{- end }}
