apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: openshift
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: multi-cluster platform configurations
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceNamespaces:
    - 'argocd-*'
  sourceRepos:
    - 'git@github.com:sean-vaughan/openshift.git'
