apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-storage
  annotations:
    olm.providedAPIs: 'LVMCluster.v1alpha1.lvm.topolvm.io,LVMVolumeGroup.v1alpha1.lvm.topolvm.io,LVMVolumeGroupNodeStatus.v1alpha1.lvm.topolvm.io,LogicalVolume.v1.topolvm.io'
  namespace: openshift-storage
spec:
  targetNamespaces:
    - openshift-storage
  upgradeStrategy: Default
