---
apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: '{{ .Values.clusterName }}'
  namespace: '{{ .Values.clusterName }}'
  labels:
    "cluster.open-cluster-management.io/clusterset": '{{ .Values.clusterSet }}'
spec:
  release:
    image: {{ .Values.image }}
  pullSecret:
    name: pull-secret
  sshKey:
    name: sshkey-cluster-hcp
  networking:
    clusterNetwork:
      - cidr: 10.132.0.0/14
    serviceNetwork:
      - cidr: {{ .Values.serviceNetwork }}
    networkType: OVNKubernetes
  controllerAvailabilityPolicy: SingleReplica
  infrastructureAvailabilityPolicy: SingleReplica
  olmCatalogPlacement: management
  platform:
    type: Agent
    agent:
      agentNamespace: '{{ .Values.clusterName }}'
  infraID: '{{ .Values.clusterName }}'
  dns:
    baseDomain: '{{ .Values.baseDomain }}'
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route