apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvm-cluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - deviceSelector:
          forceWipeDevicesAndDestroyAllData: true
          paths:
            - /dev/disk/by-id/wwn-0x6b8ca3a0eda93b002d5ae22740dc2fe3
        fstype: xfs
        name: vg1
        default: true
        thinPoolConfig:
          chunkSizeCalculationPolicy: Static
          metadataSizeCalculationPolicy: Host
          name: thin-pool-1
          overprovisionRatio: 10
          sizePercent: 90
