{{ $clusterName := .Values.clusterName }}
{{- range .Values.bareMetalHosts }}
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: {{ .hostname }}
  namespace: {{ $clusterName }}
  labels:
    nmstate-label: {{ $clusterName }}
spec:
  config:
    interfaces:
      - name: eno5
        type: ethernet
        state: up
        mac-address: {{ .mac }}
        ipv4:
          enabled: true
          dhcp: true
      - name: eno6
        type: ethernet
{{ if .storageNIC }}
        state: up
        mac-address: {{ .storageNIC.mac }}
        ipv4:
          enabled: true
          address:
            - ip: {{ .storageNIC.ip }}
              prefix-length: 24
          dhcp: false
{{ else }}
        state: down
        ipv4:
          enabled: false
{{ end }}
  interfaces:
    - name: "eno5"
      macAddress: "{{ .mac }}"
{{ if .storageNIC }}
    - name: "eno6"
      macAddress: "{{ .storageNIC.mac }}"
{{ end }}
{{- end }}
