apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-azure-secrets-provider
  namespace: azure-secrets-store-verification
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    tenantID: redhat0.onmicrosoft.com
    keyvaultName: "svaughan-kvstore-01"
    objects: |
      array:
        - |
          objectName: secret1
          objectType: secret
    tenantId: "tid"
  secretObjects:
  - secretName: secret
    type: Opaque
    data:
    - key: secret1
      objectName: secret1
