---
apiVersion: v1
kind: Namespace
metadata:
  name: mtls
  labels:
    ingress-controller: mtls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  sample-app
  namespace: mtls
  labels:
    app:  sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  sample-app
    spec:
      containers:
      - name:  sample-app
        image:  ubi9/httpd-24:latest
        resources:
          requests:
            cpu: 100m
            memory: 1000Mi
          limits:
            cpu: 100m
            memory: 1000Mi
        ports:
        - containerPort:  8080
          name:  sample-app
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: mtls
spec:
  selector:
    app: sample-app
  type: ClusterIP
  ports:
  - name: sample-app
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sample-app
  namespace: mtls
spec:
  host: sample-app-mtls.mtls.k8s-sno.vaughan.cc
  to:
    kind: Service
    name: sample-app
    weight: 100
  port:
    targetPort: sample-app
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
