apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: azure-log-forwarder
  namespace: openshift-logging
spec:
  managementState: Managed
  inputs:
    - name: reducedlogs
      type: application
      application:
        includes:
          - namespace: "openshift-*"
        excludes:
          - namespace: "cpd-operators"
          - namespace: "openshift-marketplace"
          - namespace: "openshift-operator-lifecycle-manager"
  outputs:
  - azureMonitor:
      authentication:
        sharedKey:
          key: shared_key
          secretName: azure-workspace-key
      azureResourceId: openenv-l5wl4
      customerId: 7eecb81f-7f38-48d5-9d9f-aacc310e7742
      logType: ocp
    name: azure-monitor
    type: azureMonitor
  pipelines:
  - inputRefs:
    - reducedlogs
    name: logs-to-azure
    outputRefs:
    - azure-monitor
  serviceAccount:
    name: log-collector
