apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-cluster
  namespace: '{{ .Values.clusterName }}'
spec:
  argoServer:
    cluster: local-cluster
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: default
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: default
  namespace: '{{ .Values.clusterName }}'
spec:
  clusterSets:
    - default
---
kind: ManagedClusterSetBinding
apiVersion: cluster.open-cluster-management.io/v1
metadata:
  name: default
  namespace: '{{ .Values.clusterName }}'
spec:
  clusterSet: default
