localHelmValues: true

clusterName: k8s-1
sshPublicKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOjJxh/yC65t0ZAKydvFIifj1San9Z8+no2EX0Bc0izy'
apiVIP: 10.0.2.2
ingressVIP: 10.0.2.2
machineNetwork: 192.168.86.0/24
