---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
    # This generator handles `clusters/<cluster-name>/<app-name>.yaml` files
    # which may contain argo app overrides.
    # - Simply touch the `clusters/<cluster-name><app-name>.yaml`` file to include the
    #   `apps/<app-name> on the cluster.
    # - Or, create a `clusters/*/<app-name>.yaml`` file with argo-app overrides.
    - git:
        repoURL: 'https://github.com/sean-vaughan/openshift.git'
        revision: HEAD
        files:
        - path: 'clusters/*/*.yaml'
        values:
          cluster: "{{ default (index .path.segments 1) .cluster }}"
          name: '{{ trimSuffix ".yaml" .path.filename }}'
          path: '{{ default (printf "apps/%s" (trimSuffix ".yaml" .path.filename)) .appPath }}'

  template:
    metadata:
      name: '{{ .values.name }}'
      namespace: 'argocd-{{ .values.cluster }}'
    spec:
      project: "{{ .values.cluster }}"
      source:
        repoURL: 'git@github.com:sean-vaughan/openshift.git'
        targetRevision: '{{ default "HEAD" .targetRevision }}'
        path: '{{ .values.path }}'
      destination:
        name: "{{ .values.cluster }}"
        namespace: 'argocd-{{ .values.cluster }}' # default namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 2
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true

  templatePatch: |
    {{ if or .syncPolicy .valuesFile .localHelmValues }}
    spec:
      source:
        {{ if .valuesFile }}
        helm:
          valueFiles:
          {{ if .valuesFile }}
            - '{{ .valuesFile }}'
          {{ else if .localHelmValues }}
            - '.path.path'
          {{ end }}
        {{ end }}
      {{ if .syncPolicy }}
      syncPolicy:
        {{ toYaml .syncPolicy | indent 4 }}
      {{ end }}
    {{ end }}
