---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: gitops
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:

  # The first generator case below handles `clusters/*/<app-name>.yaml` files
  # which may contain argo app overrides.
  # - Simply touch the `clusters/*/<app-name>.yaml`` file to include the app on
  #   the cluster without argo app overrides.
  # - Or, create a `clusters/*/<app-name>.yaml`` file with argo-app overrides
  #   used below.
  - git:
      repoURL: 'https://github.com/sean-vaughan/openshift.git'
      revision: HEAD
      files:
      - path: clusters/*/*.yaml
      directories:
      - path: clusters/*/*
        exclude: true
      values:
        cluster: "{{ cluster | default (index .path.segments 1) }}"
        name: "{{ .path.filename | trimSuffix '.yaml' }}"
        path: "{{ path | default (printf 'apps/%s' .values.name) }}"

  # The second generator is for 1) no <app-name>.yaml overrides, and 2) a
  # directory of yaml, or kustomize apps with local overlay files:
  - git:
      repoURL: 'https://github.com/sean-vaughan/openshift.git'
      revision: HEAD
      directories:
      - path: clusters/*/*
      # ignore helm apps
      - path: clusters/*/*/values.yaml
        exclude: true
      values:
        # cluster is defined by the `clusters/<cluster-name>` directory name.
        cluster: "{{ index .path.segments 1 }}"

        # The application name (as displayed in the ArgoCD dashboard) is defined
        # by the `clusters/<cluster-name>/<app-name>` directory name. These
        # cluster apps may be:
        # - cluster kustomizations overlayed on the base kustomization app
        #   defined in /apps/<app-name>.
        # - cluster kustomizations that don't overlay the base kustomization.
        # - or simply a directory of yaml files.
        name: "{{ index .path.segments 2 }}"
        path: "{{ .path.path }}"

  # The third generator is for 1) no `<argo-app>.yaml` overrides, and 2) helm apps
  # with a `<app-name>/values.yaml` file.
  # - git:
  #     repoURL: 'git@github.com:sean-vaughan/openshift.git'
  #     revision: HEAD
  #     files:
  #     - path: "clusters/*/*/values.yaml"
  #     directories:
  #     - path: "clusters/*/*/*/"
  #       exclude: true
  #     values:
  #       cluster: "{{ index .path.segments 1 }}"
  #       appName: "{{ index .path.segments 2 }}"
  #       appPath: "apps/{{ .values.appName }}"
  #       valuesFile: "{{ .path.path }}"
  #     template:
  #       metadata: {}
  #       spec:
  #         project: "{{ .values.cluster }}"
  #         destination: {}
  #         source:
  #           repoURL: 'git@github.com:sean-vaughan/openshift.git'
  #           targetRevision: HEAD
  #           path: '{{ .values.appPath }}'
  #           helm:
  #             valueFiles:
  #               - '{{ .values.valuesFile }}'
  #             parameters:
  #               - name: cluster
  #                 value: '{{ .values.cluster }}'

  template:
    metadata:
      name: '{{ .values.name }}'
      namespace: gitops
    spec:
      project: "{{ .values.cluster }}"
      source:
        repoURL: 'git@github.com:sean-vaughan/openshift.git'
        targetRevision: HEAD
        path: '{{ .values.path }}'
      destination:
        server: "https://kubernetes.default.svc"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 2
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true

  # templatePatch: |
  #   {{ overrides | toYaml }}
