---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-apps
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:

  # This generator is for helm app support. 1) no `<argo-app>.yaml` file
  # (overrides generator case), and 2) helm app incidated by a
  # `<clusters>/<app-name>/values.yaml` file.
  - git:
      repoURL: 'git@github.com:sean-vaughan/openshift.git'
      revision: HEAD
      files:
      - path: "clusters/*/*/values.yaml"
      directories:
      - path: "clusters/*/*/*/"
        exclude: true
      values:
        cluster: "{{ index .path.segments 1 }}"
        name: "{{ index .path.segments 2 }}"
        path: "apps/{{ .values.name }}"
        valuesFile: "{{ .path.path }}"

  template:
    metadata:
      name: '{{ .values.name }}'
      namespace: openshift-gitops
    spec:
      project: "{{ .values.cluster }}"
      source:
        repoURL: 'git@github.com:sean-vaughan/openshift.git'
        targetRevision: HEAD
        path: '{{ .values.appPath }}'
        helm:
          valueFiles:
            - '{{ .values.valuesFile }}'
          parameters:
            - name: cluster
              value: '{{ .values.cluster }}'
      destination:
        server: "https://kubernetes.default.svc"
        namespace: 'openshift-gitops' # default namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 2
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true

  # templatePatch: |
  #   {{ overrides | toYaml }}
