---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: overrides-apps
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:

  # The first generator case below handles `clusters/<cluster-name>/<app-name>.yaml` files
  # which may contain argo app overrides.
  # - Simply touch the `clusters/<cluster-name><app-name>.yaml`` file to include the
  #   `apps/<app-name> on the cluster.
  # - Or, create a `clusters/*/<app-name>.yaml`` file with argo-app overrides.
  - git:
      repoURL: 'https://github.com/sean-vaughan/openshift.git'
      revision: HEAD
      files:
      - path: clusters/*/*.yaml
      values:
        cluster: "{{ index .path.segments 1 }}"
        name: '{{ trimSuffix ".yaml" .path.filename}}'
        path: "apps/{{ .values.name }}"

  template:
    metadata:
      name: '{{ .values.name }}'
      namespace: openshift-gitops
    spec:
      project: "{{ .values.cluster }}"
      source:
        repoURL: 'git@github.com:sean-vaughan/openshift.git'
        targetRevision: HEAD
        path: '{{ .values.path }}'
      destination:
        server: "https://kubernetes.default.svc"
        namespace: 'openshift-gitops' # default namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
          limit: 2
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true

  # templatePatch: |
  #   {{ overrides | toYaml }}
